const Menu = [
    {
        id: 1,
        image: "images/biryani.jpg",
        name:"Omlet",
        category:"Breakfast",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    {
        id: 2,
        image: "images/junkfood.jpg",
        name:"Paratha",
        category:"Breakfast",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    {
        id: 3,
        image: "images/meat.jpg",
        name:"Sandwitch",
        category:"Breakfast",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    {
        id: 4,
        image: "images/piza.jpg",
        name:"Piza",
        category:"Lunch",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    {
        id: 5,
        image: "images/biryani.jpg",
        name:"Karahi",
        category:"Lunch",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    {
        id: 6,
        image: "images/junkfood.jpg",
        name:"Biryani",
        category:"Lunch",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    {
        id: 7,
        image: "images/meat.jpg",
        name:"Meat",
        category:"Dinner",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    {
        id: 8,
        image: "images/piza.jpg",
        name:"Beef",
        category:"Dinner",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    {
        id: 9,
        image: "images/biryani.jpg",
        name:"Mutton",
        category:"Dinner",
        info:"This is the most delicious food of 2022",
        price:"500",
    },
    
];

export default Menu;